### ISSUE TITLE
Question: how to use the image to manage attached volumes?

### ISSUE THREAD

**Issue by Finesse** [serversideup/docker-ssh#7]
I have a filesystem that I can't access directly, but I can mount it to a docker container as a volume. I want to use `docker-ssh` to view and edit files in the filesystem via SFTP.

<details>
<summary>More specific context</summary>

I have an AWS EFS filesystem that I want to access. I don't want to create an EC2 instance like suggested on the internet, I want to use an ECS Fargate container like the rest of my application. ECS allows to mount EFS filesystems to Docker containers as volumes.

</details>

I've succeeded to mount the filesystem to a Docker container based on the plain `serversideup/docker-ssh` image. The mount point inside the container is `/data`, I also tried `/home/tunnel/data`. When I connect to the container via SSH, I can see the mounted volume, but I can't write to it, because it's owned by `root` and the directory permissions are `755`. I tried `sudo`, but the command doesn't exist; this is not a proper option, because sudo can't be used via SFTP.

What can I do to gain a write access to the mounted directory?

**Comment by Finesse** [comment]
I've found a similar image: https://hub.docker.com/r/linuxserver/openssh-server

It allows sudo (it should be enabled via an environment variable), so I can change the owner of the mounted volume and then manage it normally.

**Comment by jaydrogers** [comment]
Thanks for bringing this to my attention!

I've been working a lot on [Spin](https://serversideup.net/open-source/spin/), [Docker PHP](https://serversideup.net/open-source/docker-php), and [Financial Freedom](https://serversideup.net/open-source/financial-freedom/), but I really would like to revisit and optimize this.

I've learned a ton since I wrote this image, and I agree -- Linuxserver.io rocks 👍

I'll keep you posted once I have a chance to take a look

**Comment by Finesse** [comment]
No worries. I realize that your image is for tunneling, not for file management, so my use-case is outside of the scope of your image.
